[package]
name = "pancake"
version = "0.1.0"
authors = ["lightning1141 <lightning1141@gmail.com>"]

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }
